In [1]:
import numpy as np
import pandas as pd
import sklearn as sk
import scipy as sp
import pickle

In [3]:
df = pd.read_csv('50_Startups.csv')
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [5]:
features = df.drop(['Profit'], axis=1)
labels = df['Profit']

numeric_features = features.select_dtypes(include=[np.number])
categorical_features = features.select_dtypes(exclude=[np.number])
numeric_features = numeric_features.fillna(numeric_features.mean(), inplace=True)
categorical_features = categorical_features.fillna(categorical_features.mode().iloc[0], inplace=True)

In [7]:
categorical_dummies = pd.get_dummies(categorical_features, drop_first=True, dtype=float)
updated_dataset = pd.concat([numeric_features, categorical_dummies], axis=1)
updated_dataset.head()

   R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0  165349.20       136897.80        471784.10            0.0             1.0
1  162597.70       151377.59        443898.53            0.0             0.0
2  153441.51       101145.55        407934.54            1.0             0.0
3  144372.41       118671.85        383199.62            0.0             1.0
4  142107.34        91391.77        366168.42            1.0             0.0

In [8]:
X_train, X_test, Y_train, Y_test = sk.model_selection.train_test_split(
    updated_dataset,
    labels,
    test_size=0.2, 
    random_state=42
)

In [10]:
model = sk.linear_model.LinearRegression()
model.fit(X_train, Y_train)
model.score(X_test, Y_test)

0.8987266414328636

In [11]:
pickle.dump(model, open('startups_model.pkl', 'wb'))